[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  publish = ".vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run build"
